releases:
  - name: postgres
    namespace: postgres
    createNamespace: true  # Auto-create if missing
    chart: charts/dependencies/postgresql
    values:
      - charts/dependencies/postgresql/values-dev.yaml